name: t_omdb
description: A simple convenience library for interacting with the OMDb API.
version: 1.0.2
repository: https://github.com/akula-shark/t-omdb

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0